# data:
dataset_root: '../data/'
dataset: "Cora"

# model:
hidden_dims: 16
num_layers: 1
dropout: 0.0
batch_norm: false
normalize_features: false

# training:
init_batch: 256
sample_size: 400
scale_factor: 1
epochs: 200
lr: 0.01
early_stop: 10
weight_decay: 0.0005
samp_inference: true
use_val: true
num_samp_inference: 1
inference_init_batch: 256
inference_sample_size: 1280
report: 1
fast: true

# system:
save_path: "./outputs/FastGCN/"
use_cuda: true
save_results: true
seed: 43
