base_dir: ./outputs/GTS/
log_level: INFO
data_para:
  batch_size: 64
  dataset_dir: ../data/METR-LA/
  dataset_file_dir: metr-la.h5
  test_batch_size: 64
  val_batch_size: 64
  graph_pkl_filename: ../data/METR-LA/sensor_graph/adj_mx.pkl # not used

model_para:
  cl_decay_steps: 2000
  filter_type: dual_random_walk
  horizon: 12
  input_dim: 2
  l1_decay: 0
  max_diffusion_step: 3
  num_nodes: 207
  num_rnn_layers: 1
  output_dim: 1
  rnn_units: 64
  seq_len: 12
  use_curriculum_learning: true
  dim_fc: 383552

train:
  base_lr: 0.005 
  dropout: 0
  epoch: 0
  epochs: 5
  epsilon: 1.0e-3
  global_step: 0
  lr_decay_ratio: 0.1
  max_grad_norm: 5
  min_learning_rate: 2.0e-06
  optimizer: adam
  patience: 100
  steps: [20, 30, 40]
  test_every_n_epochs: 5
  knn_k: 10
  epoch_use_regularization: 5
  num_sample: 10

save_results: true
